// Auto-generated from yatta.moe — 232 weapons (3★+)
// Icons: https://enka.network/ui/{icon}.png

export interface WeaponEntry {
  id: number;
  name: string;
  rarity: 3 | 4 | 5;
  type: "Sword" | "Claymore" | "Polearm" | "Bow" | "Catalyst" | "Unknown";
  substat: string;
  icon: string;
}

// Natlan morph weapon IDs — no stat data in API, filter from grid
const MORPH_IDS = new Set([310001, 310002, 320001, 320002, 330001, 330002, 340001, 340002, 350001, 350002]);

export const WEAPON_TYPES = ["All", "Sword", "Claymore", "Polearm", "Bow", "Catalyst"] as const;

export const ALL_WEAPONS: WeaponEntry[] = [
  { id: 15502, name: "Amos' Bow", rarity: 5 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Amos" },
  { id: 15508, name: "Aqua Simulacra", rarity: 5 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Kirin" },
  { id: 15514, name: "Astral Vulture's Crimson Plumage", rarity: 5 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Qoyllorsnova" },
  { id: 15503, name: "Elegy for the End", rarity: 5 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Widsith" },
  { id: 15511, name: "Hunter's Path", rarity: 5 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Ayus" },
  { id: 15507, name: "Polar Star", rarity: 5 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Worldbane" },
  { id: 15513, name: "Silvershower Heartstrings", rarity: 5 as const, type: "Bow", substat: "HP%", icon: "UI_EquipIcon_Bow_Arcdange" },
  { id: 15501, name: "Skyward Harp", rarity: 5 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Dvalin" },
  { id: 350002, name: "Starpiercer - Sublimation", rarity: 5 as const, type: "Bow", substat: "None", icon: "UI_EquipIcon_Bow_MorphChrod_Great_Wind" },
  { id: 15515, name: "The Daybreak Chronicles", rarity: 5 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Arianna" },
  { id: 15512, name: "The First Great Magic", rarity: 5 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Pledge" },
  { id: 15509, name: "Thundering Pulse", rarity: 5 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Narukami" },
  { id: 14511, name: "A Thousand Floating Dreams", rarity: 5 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Ayus" },
  { id: 14513, name: "Cashflow Supervision", rarity: 5 as const, type: "Catalyst", substat: "CRIT Rate", icon: "UI_EquipIcon_Catalyst_Wheatley" },
  { id: 14515, name: "Crane's Echoing Call", rarity: 5 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_MountainGale" },
  { id: 14506, name: "Everlasting Moonglow", rarity: 5 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_Kaleido" },
  { id: 340002, name: "Hallowed Fetters - Sublimation", rarity: 5 as const, type: "Catalyst", substat: "None", icon: "UI_EquipIcon_Catalyst_MorphIlia_Great_Wind" },
  { id: 14505, name: "Jadefall's Splendor", rarity: 5 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_Morax" },
  { id: 14509, name: "Kagura's Verity", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Narukami" },
  { id: 14502, name: "Lost Prayer to the Sacred Winds", rarity: 5 as const, type: "Catalyst", substat: "CRIT Rate", icon: "UI_EquipIcon_Catalyst_Fourwinds" },
  { id: 14504, name: "Memory of Dust", rarity: 5 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Kunwu" },
  { id: 14520, name: "Nightweaver's Looking Glass", rarity: 5 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_MenulisRing" },
  { id: 14522, name: "Nocturne's Curtain Call", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Brisingamen" },
  { id: 14521, name: "Reliquary of Truth", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Sistrum" },
  { id: 14501, name: "Skyward Atlas", rarity: 5 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Dvalin" },
  { id: 14517, name: "Starcaller's Watch", rarity: 5 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Figurines" },
  { id: 14518, name: "Sunny Morning Sleep-In", rarity: 5 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_SakuraFan" },
  { id: 14516, name: "Surf's Up", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_MechaPufferfish" },
  { id: 14514, name: "Tome of the Eternal Flow", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Iudex" },
  { id: 14512, name: "Tulaytullah's Remembrance", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Alaya" },
  { id: 14519, name: "Vivid Notions", rarity: 5 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_VaresaTransformer" },
  { id: 12514, name: "A Thousand Blazing Suns", rarity: 5 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_RadianceSword" },
  { id: 320002, name: "Ardent Storm - Sublimation", rarity: 5 as const, type: "Claymore", substat: "None", icon: "UI_EquipIcon_Claymore_MorphGravitas_Great_Wind" },
  { id: 12511, name: "Beacon of the Reed Sea", rarity: 5 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_Deshret" },
  { id: 12513, name: "Fang of the Mountain King", rarity: 5 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_EmeraldSword" },
  { id: 12515, name: "Gest of the Mighty Wolf", rarity: 5 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_EnsisAquilonis" },
  { id: 12510, name: "Redhorn Stonethresher", rarity: 5 as const, type: "Claymore", substat: "CRIT DMG", icon: "UI_EquipIcon_Claymore_Itadorimaru" },
  { id: 12501, name: "Skyward Pride", rarity: 5 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Dvalin" },
  { id: 12503, name: "Song of Broken Pines", rarity: 5 as const, type: "Claymore", substat: "Physical DMG%", icon: "UI_EquipIcon_Claymore_Widsith" },
  { id: 12504, name: "The Unforged", rarity: 5 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Kunwu" },
  { id: 12512, name: "Verdict", rarity: 5 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_GoldenVerdict" },
  { id: 12502, name: "Wolf's Gravestone", rarity: 5 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Wolfmound" },
  { id: 13516, name: "Bloodsoaked Ruins", rarity: 5 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_TummaLyhty" },
  { id: 13507, name: "Calamity Queller", rarity: 5 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Santika" },
  { id: 13512, name: "Crimson Moon's Semblance", rarity: 5 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_BloodMoon" },
  { id: 13509, name: "Engulfing Lightning", rarity: 5 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Narukami" },
  { id: 13515, name: "Fractured Halo", rarity: 5 as const, type: "Polearm", substat: "CRIT DMG", icon: "UI_EquipIcon_Pole_Perdix" },
  { id: 13513, name: "Lumidouce Elegy", rarity: 5 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Muguet" },
  { id: 13505, name: "Primordial Jade Winged-Spear", rarity: 5 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Morax" },
  { id: 330002, name: "Shattered Moon - Sublimation", rarity: 5 as const, type: "Polearm", substat: "None", icon: "UI_EquipIcon_Pole_MorphSpinifer_Great_Wind" },
  { id: 13502, name: "Skyward Spine", rarity: 5 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Dvalin" },
  { id: 13501, name: "Staff of Homa", rarity: 5 as const, type: "Polearm", substat: "CRIT DMG", icon: "UI_EquipIcon_Pole_Homa" },
  { id: 13511, name: "Staff of the Scarlet Sands", rarity: 5 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Deshret" },
  { id: 13514, name: "Symphonist of Scents", rarity: 5 as const, type: "Polearm", substat: "CRIT DMG", icon: "UI_EquipIcon_Pole_Trident" },
  { id: 13504, name: "Vortex Vanquisher", rarity: 5 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Kunwu" },
  { id: 11515, name: "Absolution", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Estoc" },
  { id: 11501, name: "Aquila Favonia", rarity: 5 as const, type: "Sword", substat: "Physical DMG%", icon: "UI_EquipIcon_Sword_Falcon" },
  { id: 11518, name: "Athame Artis", rarity: 5 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_Motsognir" },
  { id: 11517, name: "Azurelight", rarity: 5 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_OuterSword" },
  { id: 11503, name: "Freedom-Sworn", rarity: 5 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Widsith" },
  { id: 11510, name: "Haran Geppaku Futsu", rarity: 5 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_Amenoma" },
  { id: 11511, name: "Key of Khaj-Nisut", rarity: 5 as const, type: "Sword", substat: "HP%", icon: "UI_EquipIcon_Sword_Deshret" },
  { id: 11512, name: "Light of Foliar Incision", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Ayus" },
  { id: 11519, name: "Lightbearing Moonshard", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_SilverwareSaw" },
  { id: 11509, name: "Mistsplitter Reforged", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Narukami" },
  { id: 11516, name: "Peak Patrol Song", rarity: 5 as const, type: "Sword", substat: "DEF%", icon: "UI_EquipIcon_Sword_XochitlsTube" },
  { id: 11505, name: "Primordial Jade Cutter", rarity: 5 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_Morax" },
  { id: 310002, name: "Serpent Devourer - Sublimation", rarity: 5 as const, type: "Sword", substat: "None", icon: "UI_EquipIcon_Sword_MorphVinces_Great_Wind" },
  { id: 11502, name: "Skyward Blade", rarity: 5 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Dvalin" },
  { id: 11513, name: "Splendor of Tranquil Waters", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Regalis" },
  { id: 11504, name: "Summit Shaper", rarity: 5 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Kunwu" },
  { id: 11514, name: "Uraku Misugiri", rarity: 5 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Needle" },
  { id: 15410, name: "Alley Hunter", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Outlaw" },
  { id: 15408, name: "Blackcliff Warbow", rarity: 4 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Blackrock" },
  { id: 15431, name: "Chain Breaker", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Isikhulu" },
  { id: 15426, name: "Cloudforged", rarity: 4 as const, type: "Bow", substat: "Elemental Mastery", icon: "UI_EquipIcon_Bow_Ultimatum" },
  { id: 15407, name: "Compound Bow", rarity: 4 as const, type: "Bow", substat: "Physical DMG%", icon: "UI_EquipIcon_Bow_Exotic" },
  { id: 15418, name: "End of the Line", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Fin" },
  { id: 15411, name: "Fading Twilight", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Fallensun" },
  { id: 15401, name: "Favonius Warbow", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Zephyrus" },
  { id: 15430, name: "Flower-Wreathed Feathers", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Umpakati" },
  { id: 15414, name: "Hamayumi", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Bakufu" },
  { id: 15419, name: "Ibis Piercer", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Ibis" },
  { id: 15417, name: "King's Squire", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Arakalari" },
  { id: 15412, name: "Mitternachts Waltz", rarity: 4 as const, type: "Bow", substat: "Physical DMG%", icon: "UI_EquipIcon_Bow_Nachtblind" },
  { id: 15416, name: "Mouun's Moon", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Maria" },
  { id: 15415, name: "Predator", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Predator" },
  { id: 15406, name: "Prototype Crescent", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Proto" },
  { id: 15434, name: "Rainbow Serpent's Rain Bow", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_ElegguaBow" },
  { id: 15427, name: "Range Gauge", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Mechanic" },
  { id: 15404, name: "Royal Bow", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Theocrat" },
  { id: 15405, name: "Rust", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Recluse" },
  { id: 15403, name: "Sacrificial Bow", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Fossil" },
  { id: 15424, name: "Scion of the Blazing Sun", rarity: 4 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Gurabad" },
  { id: 15432, name: "Sequence of Solitude", rarity: 4 as const, type: "Bow", substat: "HP%", icon: "UI_EquipIcon_Bow_Stinger" },
  { id: 15433, name: "Snare Hook", rarity: 4 as const, type: "Bow", substat: "Energy Recharge", icon: "UI_EquipIcon_Bow_Ilmarinen" },
  { id: 15425, name: "Song of Stillness", rarity: 4 as const, type: "Bow", substat: "ATK%", icon: "UI_EquipIcon_Bow_Vorpal" },
  { id: 350001, name: "Starpiercer", rarity: 4 as const, type: "Bow", substat: "None", icon: "UI_EquipIcon_Bow_MorphChrod_Wind" },
  { id: 15402, name: "The Stringless", rarity: 4 as const, type: "Bow", substat: "Elemental Mastery", icon: "UI_EquipIcon_Bow_Troupe" },
  { id: 15409, name: "The Viridescent Hunt", rarity: 4 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Viridescent" },
  { id: 15413, name: "Windblume Ode", rarity: 4 as const, type: "Bow", substat: "Elemental Mastery", icon: "UI_EquipIcon_Bow_Fleurfair" },
  { id: 14427, name: "Ash-Graven Drinking Horn", rarity: 4 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_ConchSprayer" },
  { id: 14426, name: "Ballad of the Boundless Blue", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_DandelionPoem" },
  { id: 14408, name: "Blackcliff Agate", rarity: 4 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Blackrock" },
  { id: 14433, name: "Blackmarrow Lantern", rarity: 4 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Ilmarinen" },
  { id: 14434, name: "Dawning Frost", rarity: 4 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Ziedas" },
  { id: 14413, name: "Dodoco Tales", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Ludiharpastum" },
  { id: 14432, name: "Etherlight Spindlelute", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_SeeliesLute" },
  { id: 14409, name: "Eye of Perception", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Truelens" },
  { id: 14401, name: "Favonius Codex", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Zephyrus" },
  { id: 14425, name: "Flowing Purity", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Vorpal" },
  { id: 14412, name: "Frostbearer", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Everfrost" },
  { id: 14417, name: "Fruit of Fulfillment", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Arakalari" },
  { id: 14414, name: "Hakushin Ring", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Bakufu" },
  { id: 340001, name: "Hallowed Fetters", rarity: 4 as const, type: "Catalyst", substat: "None", icon: "UI_EquipIcon_Catalyst_MorphIlia_Wind" },
  { id: 14407, name: "Mappa Mare", rarity: 4 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Exotic" },
  { id: 14415, name: "Oathsworn Eye", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Jyanome" },
  { id: 380001, name: "Phantasmal Gift: Star Omen", rarity: 4 as const, type: "Catalyst", substat: "None", icon: "UI_EquipIcon_Catalyst_Kristall" },
  { id: 14406, name: "Prototype Amber", rarity: 4 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_Proto" },
  { id: 14431, name: "Ring of Yaxche", rarity: 4 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_Isikhulu" },
  { id: 14404, name: "Royal Grimoire", rarity: 4 as const, type: "Catalyst", substat: "ATK%", icon: "UI_EquipIcon_Catalyst_Theocrat" },
  { id: 14403, name: "Sacrificial Fragments", rarity: 4 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Fossil" },
  { id: 14424, name: "Sacrificial Jade", rarity: 4 as const, type: "Catalyst", substat: "CRIT Rate", icon: "UI_EquipIcon_Catalyst_Yue" },
  { id: 14405, name: "Solar Pearl", rarity: 4 as const, type: "Catalyst", substat: "CRIT Rate", icon: "UI_EquipIcon_Catalyst_Resurrection" },
  { id: 14402, name: "The Widsith", rarity: 4 as const, type: "Catalyst", substat: "CRIT DMG", icon: "UI_EquipIcon_Catalyst_Troupe" },
  { id: 14416, name: "Wandering Evenstar", rarity: 4 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Pleroma" },
  { id: 14430, name: "Waveriding Whirl", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Umpakati" },
  { id: 14410, name: "Wine and Song", rarity: 4 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Outlaw" },
  { id: 12416, name: "Akuoumaru", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Maria" },
  { id: 320001, name: "Ardent Storm", rarity: 4 as const, type: "Claymore", substat: "None", icon: "UI_EquipIcon_Claymore_MorphGravitas_Wind" },
  { id: 12408, name: "Blackcliff Slasher", rarity: 4 as const, type: "Claymore", substat: "CRIT DMG", icon: "UI_EquipIcon_Claymore_Blackrock" },
  { id: 12431, name: "Earth Shaker", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Isikhulu" },
  { id: 12401, name: "Favonius Greatsword", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Zephyrus" },
  { id: 12432, name: "Flame-Forged Insight", rarity: 4 as const, type: "Claymore", substat: "Elemental Mastery", icon: "UI_EquipIcon_Claymore_Polilith" },
  { id: 12417, name: "Forest Regalia", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Arakalari" },
  { id: 12430, name: "Fruitful Hook", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Umpakati" },
  { id: 12414, name: "Katsuragikiri Nagamasa", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Bakufu" },
  { id: 12410, name: "Lithic Blade", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Lapis" },
  { id: 12412, name: "Luxurious Sea-Lord", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_MillenniaTuna" },
  { id: 12418, name: "Mailed Flower", rarity: 4 as const, type: "Claymore", substat: "Elemental Mastery", icon: "UI_EquipIcon_Claymore_Fleurfair" },
  { id: 12415, name: "Makhaira Aquamarine", rarity: 4 as const, type: "Claymore", substat: "Elemental Mastery", icon: "UI_EquipIcon_Claymore_Pleroma" },
  { id: 12433, name: "Master Key", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Ilmarinen" },
  { id: 12427, name: "Portable Power Saw", rarity: 4 as const, type: "Claymore", substat: "HP%", icon: "UI_EquipIcon_Claymore_Mechanic" },
  { id: 12406, name: "Prototype Archaic", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Proto" },
  { id: 12405, name: "Rainslasher", rarity: 4 as const, type: "Claymore", substat: "Elemental Mastery", icon: "UI_EquipIcon_Claymore_Perdue" },
  { id: 12404, name: "Royal Greatsword", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Theocrat" },
  { id: 12403, name: "Sacrificial Greatsword", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Fossil" },
  { id: 12409, name: "Serpent Spine", rarity: 4 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_Kione" },
  { id: 12411, name: "Snow-Tombed Starsilver", rarity: 4 as const, type: "Claymore", substat: "Physical DMG%", icon: "UI_EquipIcon_Claymore_Dragonfell" },
  { id: 12424, name: "Talking Stick", rarity: 4 as const, type: "Claymore", substat: "CRIT Rate", icon: "UI_EquipIcon_Claymore_BeastTamer" },
  { id: 12402, name: "The Bell", rarity: 4 as const, type: "Claymore", substat: "HP%", icon: "UI_EquipIcon_Claymore_Troupe" },
  { id: 12425, name: "Tidal Shadow", rarity: 4 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Vorpal" },
  { id: 390001, name: "Unbreakable: Durandarte", rarity: 4 as const, type: "Claymore", substat: "None", icon: "UI_EquipIcon_Claymore_VarkaTunkeldegen" },
  { id: 12407, name: "Whiteblind", rarity: 4 as const, type: "Claymore", substat: "DEF%", icon: "UI_EquipIcon_Claymore_Exotic" },
  { id: 12426, name: "\"Ultimate Overlord's Mega Magic Sword\"", rarity: 4 as const, type: "Claymore", substat: "Energy Recharge", icon: "UI_EquipIcon_Claymore_Champion" },
  { id: 13424, name: "Ballad of the Fjords", rarity: 4 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Shanty" },
  { id: 13404, name: "Blackcliff Pole", rarity: 4 as const, type: "Polearm", substat: "CRIT DMG", icon: "UI_EquipIcon_Pole_Blackrock" },
  { id: 13403, name: "Crescent Pike", rarity: 4 as const, type: "Polearm", substat: "Physical DMG%", icon: "UI_EquipIcon_Pole_Exotic" },
  { id: 13405, name: "Deathmatch", rarity: 4 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Gladiator" },
  { id: 13426, name: "Dialogues of the Desert Sages", rarity: 4 as const, type: "Polearm", substat: "HP%", icon: "UI_EquipIcon_Pole_Caduceus" },
  { id: 13401, name: "Dragon's Bane", rarity: 4 as const, type: "Polearm", substat: "Elemental Mastery", icon: "UI_EquipIcon_Pole_Stardust" },
  { id: 13409, name: "Dragonspine Spear", rarity: 4 as const, type: "Polearm", substat: "Physical DMG%", icon: "UI_EquipIcon_Pole_Everfrost" },
  { id: 13407, name: "Favonius Lance", rarity: 4 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Zephyrus" },
  { id: 13431, name: "Footprint of the Rainbow", rarity: 4 as const, type: "Polearm", substat: "DEF%", icon: "UI_EquipIcon_Pole_Isikhulu" },
  { id: 13414, name: "Kitain Cross Spear", rarity: 4 as const, type: "Polearm", substat: "Elemental Mastery", icon: "UI_EquipIcon_Pole_Bakufu" },
  { id: 13406, name: "Lithic Spear", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Lapis" },
  { id: 13419, name: "Missive Windspear", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Windvane" },
  { id: 13417, name: "Moonpiercer", rarity: 4 as const, type: "Polearm", substat: "Elemental Mastery", icon: "UI_EquipIcon_Pole_Arakalari" },
  { id: 13430, name: "Mountain-Bracing Bolt", rarity: 4 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Umpakati" },
  { id: 13427, name: "Prospector's Drill", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Mechanic" },
  { id: 13433, name: "Prospector's Shovel", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Ilmarinen" },
  { id: 13402, name: "Prototype Starglitter", rarity: 4 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Proto" },
  { id: 13425, name: "Rightful Reward", rarity: 4 as const, type: "Polearm", substat: "HP%", icon: "UI_EquipIcon_Pole_Vorpal" },
  { id: 13408, name: "Royal Spear", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Theocrat" },
  { id: 13434, name: "Sacrificer's Staff", rarity: 4 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Krivule" },
  { id: 330001, name: "Shattered Moon", rarity: 4 as const, type: "Polearm", substat: "None", icon: "UI_EquipIcon_Pole_MorphSpinifer_Wind" },
  { id: 13432, name: "Tamayuratei no Ohanashi", rarity: 4 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Aoandon" },
  { id: 13416, name: "Wavebreaker's Fin", rarity: 4 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Maria" },
  { id: 13415, name: "\"The Catch\"", rarity: 4 as const, type: "Polearm", substat: "Energy Recharge", icon: "UI_EquipIcon_Pole_Mori" },
  { id: 11414, name: "Amenoma Kageuchi", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Bakufu" },
  { id: 11408, name: "Blackcliff Longsword", rarity: 4 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Blackrock" },
  { id: 11432, name: "Calamity of Eshu", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_SacrificialNgombe" },
  { id: 11415, name: "Cinnabar Spindle", rarity: 4 as const, type: "Sword", substat: "DEF%", icon: "UI_EquipIcon_Sword_Opus" },
  { id: 11401, name: "Favonius Sword", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Zephyrus" },
  { id: 11413, name: "Festering Desire", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Magnum" },
  { id: 11425, name: "Finale of the Deep", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Vorpal" },
  { id: 11426, name: "Fleuve Cendre Ferryman", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Machination" },
  { id: 11431, name: "Flute of Ezpitzal", rarity: 4 as const, type: "Sword", substat: "DEF%", icon: "UI_EquipIcon_Sword_Isikhulu" },
  { id: 11407, name: "Iron Sting", rarity: 4 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Exotic" },
  { id: 11416, name: "Kagotsurube Isshin", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Youtou" },
  { id: 11405, name: "Lion's Roar", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Rockkiller" },
  { id: 11434, name: "Moonweaver's Dawn", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Miekka" },
  { id: 11406, name: "Prototype Rancour", rarity: 4 as const, type: "Sword", substat: "Physical DMG%", icon: "UI_EquipIcon_Sword_Proto" },
  { id: 11404, name: "Royal Longsword", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Theocrat" },
  { id: 11403, name: "Sacrificial Sword", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Fossil" },
  { id: 11417, name: "Sapwood Blade", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Arakalari" },
  { id: 11433, name: "Serenity's Call", rarity: 4 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Ilmarinen" },
  { id: 310001, name: "Serpent Devourer", rarity: 4 as const, type: "Sword", substat: "None", icon: "UI_EquipIcon_Sword_MorphVinces_Wind" },
  { id: 11430, name: "Sturdy Bone", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Umpakati" },
  { id: 11412, name: "Sword of Descension", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Psalmus" },
  { id: 11428, name: "Sword of Narzissenkreuz", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Purewill" },
  { id: 11410, name: "The Alley Flash", rarity: 4 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Outlaw" },
  { id: 11409, name: "The Black Sword", rarity: 4 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_Bloodstained" },
  { id: 11427, name: "The Dockhand's Assistant", rarity: 4 as const, type: "Sword", substat: "HP%", icon: "UI_EquipIcon_Sword_Mechanic" },
  { id: 11402, name: "The Flute", rarity: 4 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Troupe" },
  { id: 11422, name: "Toukabou Shigure", rarity: 4 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Kasabouzu" },
  { id: 11424, name: "Wolf-Fang", rarity: 4 as const, type: "Sword", substat: "CRIT Rate", icon: "UI_EquipIcon_Sword_Boreas" },
  { id: 11418, name: "Xiphos' Moonlight", rarity: 4 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Pleroma" },
  { id: 15305, name: "Messenger", rarity: 3 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Msg" },
  { id: 15301, name: "Raven Bow", rarity: 3 as const, type: "Bow", substat: "Elemental Mastery", icon: "UI_EquipIcon_Bow_Crowfeather" },
  { id: 15303, name: "Recurve Bow", rarity: 3 as const, type: "Bow", substat: "HP%", icon: "UI_EquipIcon_Bow_Curve" },
  { id: 15302, name: "Sharpshooter's Oath", rarity: 3 as const, type: "Bow", substat: "CRIT DMG", icon: "UI_EquipIcon_Bow_Arjuna" },
  { id: 15304, name: "Slingshot", rarity: 3 as const, type: "Bow", substat: "CRIT Rate", icon: "UI_EquipIcon_Bow_Sling" },
  { id: 14304, name: "Emerald Orb", rarity: 3 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Jade" },
  { id: 14301, name: "Magic Guide", rarity: 3 as const, type: "Catalyst", substat: "Elemental Mastery", icon: "UI_EquipIcon_Catalyst_Intro" },
  { id: 14303, name: "Otherworldly Story", rarity: 3 as const, type: "Catalyst", substat: "Energy Recharge", icon: "UI_EquipIcon_Catalyst_Lightnov" },
  { id: 14302, name: "Thrilling Tales of Dragon Slayers", rarity: 3 as const, type: "Catalyst", substat: "HP%", icon: "UI_EquipIcon_Catalyst_Pulpfic" },
  { id: 14305, name: "Twin Nephrite", rarity: 3 as const, type: "Catalyst", substat: "CRIT Rate", icon: "UI_EquipIcon_Catalyst_Phoney" },
  { id: 12302, name: "Bloodtainted Greatsword", rarity: 3 as const, type: "Claymore", substat: "Elemental Mastery", icon: "UI_EquipIcon_Claymore_Siegfry" },
  { id: 12305, name: "Debate Club", rarity: 3 as const, type: "Claymore", substat: "ATK%", icon: "UI_EquipIcon_Claymore_Reasoning" },
  { id: 12301, name: "Ferrous Shadow", rarity: 3 as const, type: "Claymore", substat: "HP%", icon: "UI_EquipIcon_Claymore_Glaive" },
  { id: 12306, name: "Skyrider Greatsword", rarity: 3 as const, type: "Claymore", substat: "Physical DMG%", icon: "UI_EquipIcon_Claymore_Mitsurugi" },
  { id: 12303, name: "White Iron Greatsword", rarity: 3 as const, type: "Claymore", substat: "DEF%", icon: "UI_EquipIcon_Claymore_Tin" },
  { id: 13303, name: "Black Tassel", rarity: 3 as const, type: "Polearm", substat: "HP%", icon: "UI_EquipIcon_Pole_Noire" },
  { id: 13302, name: "Halberd", rarity: 3 as const, type: "Polearm", substat: "ATK%", icon: "UI_EquipIcon_Pole_Halberd" },
  { id: 13301, name: "White Tassel", rarity: 3 as const, type: "Polearm", substat: "CRIT Rate", icon: "UI_EquipIcon_Pole_Ruby" },
  { id: 11301, name: "Cool Steel", rarity: 3 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Steel" },
  { id: 11304, name: "Dark Iron Sword", rarity: 3 as const, type: "Sword", substat: "Elemental Mastery", icon: "UI_EquipIcon_Sword_Darker" },
  { id: 11305, name: "Fillet Blade", rarity: 3 as const, type: "Sword", substat: "ATK%", icon: "UI_EquipIcon_Sword_Sashimi" },
  { id: 11302, name: "Harbinger of Dawn", rarity: 3 as const, type: "Sword", substat: "CRIT DMG", icon: "UI_EquipIcon_Sword_Dawn" },
  { id: 11306, name: "Skyrider Sword", rarity: 3 as const, type: "Sword", substat: "Energy Recharge", icon: "UI_EquipIcon_Sword_Mitsurugi" },
  { id: 11303, name: "Traveler's Handy Sword", rarity: 3 as const, type: "Sword", substat: "DEF%", icon: "UI_EquipIcon_Sword_Traveler" },
];


export const DISPLAYABLE_WEAPONS = ALL_WEAPONS.filter(w => !MORPH_IDS.has(w.id));
