#!/usr/bin/env node
import { writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';

const YATTA_CDN = 'https://gi.yatta.moe/assets/UI';
const PUBLIC = './public/assets';

// Character data — extracted from src/lib/characters.ts (111 characters)
// Format: { id, avatarKey, icon, sideIcon }
const CHARACTERS = [
  { id: "10000003", avatarKey: "Qin", icon: "UI_AvatarIcon_Qin", sideIcon: "UI_AvatarIcon_Side_Qin" },
  { id: "10000006", avatarKey: "Lisa", icon: "UI_AvatarIcon_Lisa", sideIcon: "UI_AvatarIcon_Side_Lisa" },
  { id: "10000014", avatarKey: "Barbara", icon: "UI_AvatarIcon_Barbara", sideIcon: "UI_AvatarIcon_Side_Barbara" },
  { id: "10000015", avatarKey: "Kaeya", icon: "UI_AvatarIcon_Kaeya", sideIcon: "UI_AvatarIcon_Side_Kaeya" },
  { id: "10000016", avatarKey: "Diluc", icon: "UI_AvatarIcon_Diluc", sideIcon: "UI_AvatarIcon_Side_Diluc" },
  { id: "10000020", avatarKey: "Razor", icon: "UI_AvatarIcon_Razor", sideIcon: "UI_AvatarIcon_Side_Razor" },
  { id: "10000021", avatarKey: "Ambor", icon: "UI_AvatarIcon_Ambor", sideIcon: "UI_AvatarIcon_Side_Ambor" },
  { id: "10000022", avatarKey: "Venti", icon: "UI_AvatarIcon_Venti", sideIcon: "UI_AvatarIcon_Side_Venti" },
  { id: "10000023", avatarKey: "Xiangling", icon: "UI_AvatarIcon_Xiangling", sideIcon: "UI_AvatarIcon_Side_Xiangling" },
  { id: "10000024", avatarKey: "Beidou", icon: "UI_AvatarIcon_Beidou", sideIcon: "UI_AvatarIcon_Side_Beidou" },
  { id: "10000025", avatarKey: "Xingqiu", icon: "UI_AvatarIcon_Xingqiu", sideIcon: "UI_AvatarIcon_Side_Xingqiu" },
  { id: "10000027", avatarKey: "Ningguang", icon: "UI_AvatarIcon_Ningguang", sideIcon: "UI_AvatarIcon_Side_Ningguang" },
  { id: "10000029", avatarKey: "Klee", icon: "UI_AvatarIcon_Klee", sideIcon: "UI_AvatarIcon_Side_Klee" },
  { id: "10000031", avatarKey: "Fischl", icon: "UI_AvatarIcon_Fischl", sideIcon: "UI_AvatarIcon_Side_Fischl" },
  { id: "10000032", avatarKey: "Bennett", icon: "UI_AvatarIcon_Bennett", sideIcon: "UI_AvatarIcon_Side_Bennett" },
  { id: "10000034", avatarKey: "Noel", icon: "UI_AvatarIcon_Noel", sideIcon: "UI_AvatarIcon_Side_Noel" },
  { id: "10000035", avatarKey: "Qiqi", icon: "UI_AvatarIcon_Qiqi", sideIcon: "UI_AvatarIcon_Side_Qiqi" },
  { id: "10000036", avatarKey: "Chongyun", icon: "UI_AvatarIcon_Chongyun", sideIcon: "UI_AvatarIcon_Side_Chongyun" },
  { id: "10000041", avatarKey: "Mona", icon: "UI_AvatarIcon_Mona", sideIcon: "UI_AvatarIcon_Side_Mona" },
  { id: "10000042", avatarKey: "Keqing", icon: "UI_AvatarIcon_Keqing", sideIcon: "UI_AvatarIcon_Side_Keqing" },
  { id: "10000043", avatarKey: "Sucrose", icon: "UI_AvatarIcon_Sucrose", sideIcon: "UI_AvatarIcon_Side_Sucrose" },
  { id: "10000033", avatarKey: "Tartaglia", icon: "UI_AvatarIcon_Tartaglia", sideIcon: "UI_AvatarIcon_Side_Tartaglia" },
  { id: "10000039", avatarKey: "Diona", icon: "UI_AvatarIcon_Diona", sideIcon: "UI_AvatarIcon_Side_Diona" },
  { id: "10000030", avatarKey: "Zhongli", icon: "UI_AvatarIcon_Zhongli", sideIcon: "UI_AvatarIcon_Side_Zhongli" },
  { id: "10000044", avatarKey: "Xinyan", icon: "UI_AvatarIcon_Xinyan", sideIcon: "UI_AvatarIcon_Side_Xinyan" },
  { id: "10000038", avatarKey: "Albedo", icon: "UI_AvatarIcon_Albedo", sideIcon: "UI_AvatarIcon_Side_Albedo" },
  { id: "10000037", avatarKey: "Ganyu", icon: "UI_AvatarIcon_Ganyu", sideIcon: "UI_AvatarIcon_Side_Ganyu" },
  { id: "10000026", avatarKey: "Xiao", icon: "UI_AvatarIcon_Xiao", sideIcon: "UI_AvatarIcon_Side_Xiao" },
  { id: "10000046", avatarKey: "Hutao", icon: "UI_AvatarIcon_Hutao", sideIcon: "UI_AvatarIcon_Side_Hutao" },
  { id: "10000045", avatarKey: "Rosaria", icon: "UI_AvatarIcon_Rosaria", sideIcon: "UI_AvatarIcon_Side_Rosaria" },
  { id: "10000048", avatarKey: "Feiyan", icon: "UI_AvatarIcon_Feiyan", sideIcon: "UI_AvatarIcon_Side_Feiyan" },
  { id: "10000051", avatarKey: "Eula", icon: "UI_AvatarIcon_Eula", sideIcon: "UI_AvatarIcon_Side_Eula" },
  { id: "10000047", avatarKey: "Kazuha", icon: "UI_AvatarIcon_Kazuha", sideIcon: "UI_AvatarIcon_Side_Kazuha" },
  { id: "10000002", avatarKey: "Ayaka", icon: "UI_AvatarIcon_Ayaka", sideIcon: "UI_AvatarIcon_Side_Ayaka" },
  { id: "10000049", avatarKey: "Yoimiya", icon: "UI_AvatarIcon_Yoimiya", sideIcon: "UI_AvatarIcon_Side_Yoimiya" },
  { id: "10000053", avatarKey: "Sayu", icon: "UI_AvatarIcon_Sayu", sideIcon: "UI_AvatarIcon_Side_Sayu" },
  { id: "10000052", avatarKey: "Shougun", icon: "UI_AvatarIcon_Shougun", sideIcon: "UI_AvatarIcon_Side_Shougun" },
  { id: "10000056", avatarKey: "Sara", icon: "UI_AvatarIcon_Sara", sideIcon: "UI_AvatarIcon_Side_Sara" },
  { id: "10000062", avatarKey: "Aloy", icon: "UI_AvatarIcon_Aloy", sideIcon: "UI_AvatarIcon_Side_Aloy" },
  { id: "10000054", avatarKey: "Kokomi", icon: "UI_AvatarIcon_Kokomi", sideIcon: "UI_AvatarIcon_Side_Kokomi" },
  { id: "10000050", avatarKey: "Tohma", icon: "UI_AvatarIcon_Tohma", sideIcon: "UI_AvatarIcon_Side_Tohma" },
  { id: "10000055", avatarKey: "Gorou", icon: "UI_AvatarIcon_Gorou", sideIcon: "UI_AvatarIcon_Side_Gorou" },
  { id: "10000057", avatarKey: "Itto", icon: "UI_AvatarIcon_Itto", sideIcon: "UI_AvatarIcon_Side_Itto" },
  { id: "10000063", avatarKey: "Shenhe", icon: "UI_AvatarIcon_Shenhe", sideIcon: "UI_AvatarIcon_Side_Shenhe" },
  { id: "10000064", avatarKey: "Yunjin", icon: "UI_AvatarIcon_Yunjin", sideIcon: "UI_AvatarIcon_Side_Yunjin" },
  { id: "10000058", avatarKey: "Yae", icon: "UI_AvatarIcon_Yae", sideIcon: "UI_AvatarIcon_Side_Yae" },
  { id: "10000066", avatarKey: "Ayato", icon: "UI_AvatarIcon_Ayato", sideIcon: "UI_AvatarIcon_Side_Ayato" },
  { id: "10000060", avatarKey: "Yelan", icon: "UI_AvatarIcon_Yelan", sideIcon: "UI_AvatarIcon_Side_Yelan" },
  { id: "10000065", avatarKey: "Shinobu", icon: "UI_AvatarIcon_Shinobu", sideIcon: "UI_AvatarIcon_Side_Shinobu" },
  { id: "10000059", avatarKey: "Heizo", icon: "UI_AvatarIcon_Heizo", sideIcon: "UI_AvatarIcon_Side_Heizo" },
  { id: "10000067", avatarKey: "Collei", icon: "UI_AvatarIcon_Collei", sideIcon: "UI_AvatarIcon_Side_Collei" },
  { id: "10000069", avatarKey: "Tighnari", icon: "UI_AvatarIcon_Tighnari", sideIcon: "UI_AvatarIcon_Side_Tighnari" },
  { id: "10000068", avatarKey: "Dori", icon: "UI_AvatarIcon_Dori", sideIcon: "UI_AvatarIcon_Side_Dori" },
  { id: "10000071", avatarKey: "Cyno", icon: "UI_AvatarIcon_Cyno", sideIcon: "UI_AvatarIcon_Side_Cyno" },
  { id: "10000072", avatarKey: "Candace", icon: "UI_AvatarIcon_Candace", sideIcon: "UI_AvatarIcon_Side_Candace" },
  { id: "10000070", avatarKey: "Nilou", icon: "UI_AvatarIcon_Nilou", sideIcon: "UI_AvatarIcon_Side_Nilou" },
  { id: "10000073", avatarKey: "Nahida", icon: "UI_AvatarIcon_Nahida", sideIcon: "UI_AvatarIcon_Side_Nahida" },
  { id: "10000074", avatarKey: "Layla", icon: "UI_AvatarIcon_Layla", sideIcon: "UI_AvatarIcon_Side_Layla" },
  { id: "10000075", avatarKey: "Wanderer", icon: "UI_AvatarIcon_Wanderer", sideIcon: "UI_AvatarIcon_Side_Wanderer" },
  { id: "10000076", avatarKey: "Faruzan", icon: "UI_AvatarIcon_Faruzan", sideIcon: "UI_AvatarIcon_Side_Faruzan" },
  { id: "10000077", avatarKey: "Yaoyao", icon: "UI_AvatarIcon_Yaoyao", sideIcon: "UI_AvatarIcon_Side_Yaoyao" },
  { id: "10000078", avatarKey: "Alhatham", icon: "UI_AvatarIcon_Alhatham", sideIcon: "UI_AvatarIcon_Side_Alhatham" },
  { id: "10000079", avatarKey: "Dehya", icon: "UI_AvatarIcon_Dehya", sideIcon: "UI_AvatarIcon_Side_Dehya" },
  { id: "10000080", avatarKey: "Mika", icon: "UI_AvatarIcon_Mika", sideIcon: "UI_AvatarIcon_Side_Mika" },
  { id: "10000081", avatarKey: "Kaveh", icon: "UI_AvatarIcon_Kaveh", sideIcon: "UI_AvatarIcon_Side_Kaveh" },
  { id: "10000082", avatarKey: "Baizhuer", icon: "UI_AvatarIcon_Baizhuer", sideIcon: "UI_AvatarIcon_Side_Baizhuer" },
  { id: "10000061", avatarKey: "Momoka", icon: "UI_AvatarIcon_Momoka", sideIcon: "UI_AvatarIcon_Side_Momoka" },
  { id: "10000083", avatarKey: "Linette", icon: "UI_AvatarIcon_Linette", sideIcon: "UI_AvatarIcon_Side_Linette" },
  { id: "10000084", avatarKey: "Liney", icon: "UI_AvatarIcon_Liney", sideIcon: "UI_AvatarIcon_Side_Liney" },
  { id: "10000085", avatarKey: "Freminet", icon: "UI_AvatarIcon_Freminet", sideIcon: "UI_AvatarIcon_Side_Freminet" },
  { id: "10000087", avatarKey: "Neuvillette", icon: "UI_AvatarIcon_Neuvillette", sideIcon: "UI_AvatarIcon_Side_Neuvillette" },
  { id: "10000086", avatarKey: "Wriothesley", icon: "UI_AvatarIcon_Wriothesley", sideIcon: "UI_AvatarIcon_Side_Wriothesley" },
  { id: "10000088", avatarKey: "Charlotte", icon: "UI_AvatarIcon_Charlotte", sideIcon: "UI_AvatarIcon_Side_Charlotte" },
  { id: "10000089", avatarKey: "Furina", icon: "UI_AvatarIcon_Furina", sideIcon: "UI_AvatarIcon_Side_Furina" },
  { id: "10000091", avatarKey: "Navia", icon: "UI_AvatarIcon_Navia", sideIcon: "UI_AvatarIcon_Side_Navia" },
  { id: "10000090", avatarKey: "Chevreuse", icon: "UI_AvatarIcon_Chevreuse", sideIcon: "UI_AvatarIcon_Side_Chevreuse" },
  { id: "10000092", avatarKey: "Gaming", icon: "UI_AvatarIcon_Gaming", sideIcon: "UI_AvatarIcon_Side_Gaming" },
  { id: "10000093", avatarKey: "Liuyun", icon: "UI_AvatarIcon_Liuyun", sideIcon: "UI_AvatarIcon_Side_Liuyun" },
  { id: "10000094", avatarKey: "Chiori", icon: "UI_AvatarIcon_Chiori", sideIcon: "UI_AvatarIcon_Side_Chiori" },
  { id: "10000096", avatarKey: "Arlecchino", icon: "UI_AvatarIcon_Arlecchino", sideIcon: "UI_AvatarIcon_Side_Arlecchino" },
  { id: "10000097", avatarKey: "Sethos", icon: "UI_AvatarIcon_Sethos", sideIcon: "UI_AvatarIcon_Side_Sethos" },
  { id: "10000098", avatarKey: "Clorinde", icon: "UI_AvatarIcon_Clorinde", sideIcon: "UI_AvatarIcon_Side_Clorinde" },
  { id: "10000095", avatarKey: "Sigewinne", icon: "UI_AvatarIcon_Sigewinne", sideIcon: "UI_AvatarIcon_Side_Sigewinne" },
  { id: "10000099", avatarKey: "Emilie", icon: "UI_AvatarIcon_Emilie", sideIcon: "UI_AvatarIcon_Side_Emilie" },
  { id: "10000100", avatarKey: "Kachina", icon: "UI_AvatarIcon_Kachina", sideIcon: "UI_AvatarIcon_Side_Kachina" },
  { id: "10000102", avatarKey: "Mualani", icon: "UI_AvatarIcon_Mualani", sideIcon: "UI_AvatarIcon_Side_Mualani" },
  { id: "10000101", avatarKey: "Kinich", icon: "UI_AvatarIcon_Kinich", sideIcon: "UI_AvatarIcon_Side_Kinich" },
  { id: "10000103", avatarKey: "Xilonen", icon: "UI_AvatarIcon_Xilonen", sideIcon: "UI_AvatarIcon_Side_Xilonen" },
  { id: "10000104", avatarKey: "Chasca", icon: "UI_AvatarIcon_Chasca", sideIcon: "UI_AvatarIcon_Side_Chasca" },
  { id: "10000105", avatarKey: "Olorun", icon: "UI_AvatarIcon_Olorun", sideIcon: "UI_AvatarIcon_Side_Olorun" },
  { id: "10000106", avatarKey: "Mavuika", icon: "UI_AvatarIcon_Mavuika", sideIcon: "UI_AvatarIcon_Side_Mavuika" },
  { id: "10000107", avatarKey: "Citlali", icon: "UI_AvatarIcon_Citlali", sideIcon: "UI_AvatarIcon_Side_Citlali" },
  { id: "10000108", avatarKey: "Lanyan", icon: "UI_AvatarIcon_Lanyan", sideIcon: "UI_AvatarIcon_Side_Lanyan" },
  { id: "10000109", avatarKey: "Mizuki", icon: "UI_AvatarIcon_Mizuki", sideIcon: "UI_AvatarIcon_Side_Mizuki" },
  { id: "10000110", avatarKey: "Iansan", icon: "UI_AvatarIcon_Iansan", sideIcon: "UI_AvatarIcon_Side_Iansan" },
  { id: "10000111", avatarKey: "Varesa", icon: "UI_AvatarIcon_Varesa", sideIcon: "UI_AvatarIcon_Side_Varesa" },
  { id: "10000112", avatarKey: "Escoffier", icon: "UI_AvatarIcon_Escoffier", sideIcon: "UI_AvatarIcon_Side_Escoffier" },
  { id: "10000113", avatarKey: "Ifa", icon: "UI_AvatarIcon_Ifa", sideIcon: "UI_AvatarIcon_Side_Ifa" },
  { id: "10000114", avatarKey: "SkirkNew", icon: "UI_AvatarIcon_SkirkNew", sideIcon: "UI_AvatarIcon_Side_SkirkNew" },
  { id: "10000115", avatarKey: "Dahlia", icon: "UI_AvatarIcon_Dahlia", sideIcon: "UI_AvatarIcon_Side_Dahlia" },
  { id: "10000116", avatarKey: "Ineffa", icon: "UI_AvatarIcon_Ineffa", sideIcon: "UI_AvatarIcon_Side_Ineffa" },
  { id: "10000119", avatarKey: "Lauma", icon: "UI_AvatarIcon_Lauma", sideIcon: "UI_AvatarIcon_Side_Lauma" },
  { id: "10000121", avatarKey: "Aino", icon: "UI_AvatarIcon_Aino", sideIcon: "UI_AvatarIcon_Side_Aino" },
  { id: "10000120", avatarKey: "Flins", icon: "UI_AvatarIcon_Flins", sideIcon: "UI_AvatarIcon_Side_Flins" },
  { id: "10000122", avatarKey: "Nefer", icon: "UI_AvatarIcon_Nefer", sideIcon: "UI_AvatarIcon_Side_Nefer" },
  { id: "10000123", avatarKey: "Durin", icon: "UI_AvatarIcon_Durin", sideIcon: "UI_AvatarIcon_Side_Durin" },
  { id: "10000124", avatarKey: "Jahoda", icon: "UI_AvatarIcon_Jahoda", sideIcon: "UI_AvatarIcon_Side_Jahoda" },
  { id: "10000125", avatarKey: "Columbina", icon: "UI_AvatarIcon_Columbina", sideIcon: "UI_AvatarIcon_Side_Columbina" },
  { id: "10000126", avatarKey: "Zibai", icon: "UI_AvatarIcon_Zibai", sideIcon: "UI_AvatarIcon_Side_Zibai" },
  { id: "10000127", avatarKey: "Illuga", icon: "UI_AvatarIcon_Illuga", sideIcon: "UI_AvatarIcon_Side_Illuga" },
  { id: "10000128", avatarKey: "Varka", icon: "UI_AvatarIcon_Varka", sideIcon: "UI_AvatarIcon_Side_Varka" },
];

// Weapon data — extracted from src/lib/weapons.ts (232 weapons)
// Format: { id, icon }
const WEAPONS = [
  { id: 15502, icon: "UI_EquipIcon_Bow_Amos" },
  { id: 15508, icon: "UI_EquipIcon_Bow_Kirin" },
  { id: 15514, icon: "UI_EquipIcon_Bow_Qoyllorsnova" },
  { id: 15503, icon: "UI_EquipIcon_Bow_Widsith" },
  { id: 15511, icon: "UI_EquipIcon_Bow_Ayus" },
  { id: 15507, icon: "UI_EquipIcon_Bow_Worldbane" },
  { id: 15513, icon: "UI_EquipIcon_Bow_Arcdange" },
  { id: 15501, icon: "UI_EquipIcon_Bow_Dvalin" },
  { id: 350002, icon: "UI_EquipIcon_Bow_MorphChrod_Great_Wind" },
  { id: 15515, icon: "UI_EquipIcon_Bow_Arianna" },
  { id: 15512, icon: "UI_EquipIcon_Bow_Pledge" },
  { id: 15509, icon: "UI_EquipIcon_Bow_Narukami" },
  { id: 14511, icon: "UI_EquipIcon_Catalyst_Ayus" },
  { id: 14513, icon: "UI_EquipIcon_Catalyst_Wheatley" },
  { id: 14515, icon: "UI_EquipIcon_Catalyst_MountainGale" },
  { id: 14506, icon: "UI_EquipIcon_Catalyst_Kaleido" },
  { id: 340002, icon: "UI_EquipIcon_Catalyst_MorphIlia_Great_Wind" },
  { id: 14505, icon: "UI_EquipIcon_Catalyst_Morax" },
  { id: 14509, icon: "UI_EquipIcon_Catalyst_Narukami" },
  { id: 14502, icon: "UI_EquipIcon_Catalyst_Fourwinds" },
  { id: 14504, icon: "UI_EquipIcon_Catalyst_Kunwu" },
  { id: 14520, icon: "UI_EquipIcon_Catalyst_MenulisRing" },
  { id: 14522, icon: "UI_EquipIcon_Catalyst_Brisingamen" },
  { id: 14521, icon: "UI_EquipIcon_Catalyst_Sistrum" },
  { id: 14501, icon: "UI_EquipIcon_Catalyst_Dvalin" },
  { id: 14517, icon: "UI_EquipIcon_Catalyst_Figurines" },
  { id: 14518, icon: "UI_EquipIcon_Catalyst_SakuraFan" },
  { id: 14516, icon: "UI_EquipIcon_Catalyst_MechaPufferfish" },
  { id: 14514, icon: "UI_EquipIcon_Catalyst_Iudex" },
  { id: 14512, icon: "UI_EquipIcon_Catalyst_Alaya" },
  { id: 14519, icon: "UI_EquipIcon_Catalyst_VaresaTransformer" },
  { id: 12514, icon: "UI_EquipIcon_Claymore_RadianceSword" },
  { id: 320002, icon: "UI_EquipIcon_Claymore_MorphGravitas_Great_Wind" },
  { id: 12511, icon: "UI_EquipIcon_Claymore_Deshret" },
  { id: 12513, icon: "UI_EquipIcon_Claymore_EmeraldSword" },
  { id: 12515, icon: "UI_EquipIcon_Claymore_EnsisAquilonis" },
  { id: 12510, icon: "UI_EquipIcon_Claymore_Itadorimaru" },
  { id: 12501, icon: "UI_EquipIcon_Claymore_Dvalin" },
  { id: 12503, icon: "UI_EquipIcon_Claymore_Widsith" },
  { id: 12504, icon: "UI_EquipIcon_Claymore_Kunwu" },
  { id: 12512, icon: "UI_EquipIcon_Claymore_GoldenVerdict" },
  { id: 12502, icon: "UI_EquipIcon_Claymore_Wolfmound" },
  { id: 13516, icon: "UI_EquipIcon_Pole_TummaLyhty" },
  { id: 13507, icon: "UI_EquipIcon_Pole_Santika" },
  { id: 13512, icon: "UI_EquipIcon_Pole_BloodMoon" },
  { id: 13509, icon: "UI_EquipIcon_Pole_Narukami" },
  { id: 13515, icon: "UI_EquipIcon_Pole_Perdix" },
  { id: 13513, icon: "UI_EquipIcon_Pole_Muguet" },
  { id: 13505, icon: "UI_EquipIcon_Pole_Morax" },
  { id: 330002, icon: "UI_EquipIcon_Pole_MorphSpinifer_Great_Wind" },
  { id: 13502, icon: "UI_EquipIcon_Pole_Dvalin" },
  { id: 13501, icon: "UI_EquipIcon_Pole_Homa" },
  { id: 13511, icon: "UI_EquipIcon_Pole_Deshret" },
  { id: 13514, icon: "UI_EquipIcon_Pole_Trident" },
  { id: 13504, icon: "UI_EquipIcon_Pole_Kunwu" },
  { id: 11515, icon: "UI_EquipIcon_Sword_Estoc" },
  { id: 11501, icon: "UI_EquipIcon_Sword_Falcon" },
  { id: 11518, icon: "UI_EquipIcon_Sword_Motsognir" },
  { id: 11517, icon: "UI_EquipIcon_Sword_OuterSword" },
  { id: 11503, icon: "UI_EquipIcon_Sword_Widsith" },
  { id: 11510, icon: "UI_EquipIcon_Sword_Amenoma" },
  { id: 11511, icon: "UI_EquipIcon_Sword_Deshret" },
  { id: 11512, icon: "UI_EquipIcon_Sword_Ayus" },
  { id: 11519, icon: "UI_EquipIcon_Sword_SilverwareSaw" },
  { id: 11509, icon: "UI_EquipIcon_Sword_Narukami" },
  { id: 11516, icon: "UI_EquipIcon_Sword_XochitlsTube" },
  { id: 11505, icon: "UI_EquipIcon_Sword_Morax" },
  { id: 310002, icon: "UI_EquipIcon_Sword_MorphVinces_Great_Wind" },
  { id: 11502, icon: "UI_EquipIcon_Sword_Dvalin" },
  { id: 11513, icon: "UI_EquipIcon_Sword_Regalis" },
  { id: 11504, icon: "UI_EquipIcon_Sword_Kunwu" },
  { id: 11514, icon: "UI_EquipIcon_Sword_Needle" },
  { id: 15410, icon: "UI_EquipIcon_Bow_Outlaw" },
  { id: 15408, icon: "UI_EquipIcon_Bow_Blackrock" },
  { id: 15431, icon: "UI_EquipIcon_Bow_Isikhulu" },
  { id: 15426, icon: "UI_EquipIcon_Bow_Ultimatum" },
  { id: 15407, icon: "UI_EquipIcon_Bow_Exotic" },
  { id: 15418, icon: "UI_EquipIcon_Bow_Fin" },
  { id: 15411, icon: "UI_EquipIcon_Bow_Fallensun" },
  { id: 15401, icon: "UI_EquipIcon_Bow_Zephyrus" },
  { id: 15430, icon: "UI_EquipIcon_Bow_Umpakati" },
  { id: 15414, icon: "UI_EquipIcon_Bow_Bakufu" },
  { id: 15419, icon: "UI_EquipIcon_Bow_Ibis" },
  { id: 15417, icon: "UI_EquipIcon_Bow_Arakalari" },
  { id: 15412, icon: "UI_EquipIcon_Bow_Nachtblind" },
  { id: 15416, icon: "UI_EquipIcon_Bow_Maria" },
  { id: 15415, icon: "UI_EquipIcon_Bow_Predator" },
  { id: 15406, icon: "UI_EquipIcon_Bow_Proto" },
  { id: 15434, icon: "UI_EquipIcon_Bow_ElegguaBow" },
  { id: 15427, icon: "UI_EquipIcon_Bow_Mechanic" },
  { id: 15404, icon: "UI_EquipIcon_Bow_Theocrat" },
  { id: 15405, icon: "UI_EquipIcon_Bow_Recluse" },
  { id: 15403, icon: "UI_EquipIcon_Bow_Fossil" },
  { id: 15424, icon: "UI_EquipIcon_Bow_Gurabad" },
  { id: 15432, icon: "UI_EquipIcon_Bow_Stinger" },
  { id: 15433, icon: "UI_EquipIcon_Bow_Ilmarinen" },
  { id: 15425, icon: "UI_EquipIcon_Bow_Vorpal" },
  { id: 350001, icon: "UI_EquipIcon_Bow_MorphChrod_Wind" },
  { id: 15402, icon: "UI_EquipIcon_Bow_Troupe" },
  { id: 15409, icon: "UI_EquipIcon_Bow_Viridescent" },
  { id: 15413, icon: "UI_EquipIcon_Bow_Fleurfair" },
  { id: 14427, icon: "UI_EquipIcon_Catalyst_ConchSprayer" },
  { id: 14426, icon: "UI_EquipIcon_Catalyst_DandelionPoem" },
  { id: 14408, icon: "UI_EquipIcon_Catalyst_Blackrock" },
  { id: 14433, icon: "UI_EquipIcon_Catalyst_Ilmarinen" },
  { id: 14434, icon: "UI_EquipIcon_Catalyst_Ziedas" },
  { id: 14413, icon: "UI_EquipIcon_Catalyst_Ludiharpastum" },
  { id: 14432, icon: "UI_EquipIcon_Catalyst_SeeliesLute" },
  { id: 14409, icon: "UI_EquipIcon_Catalyst_Truelens" },
  { id: 14401, icon: "UI_EquipIcon_Catalyst_Zephyrus" },
  { id: 14425, icon: "UI_EquipIcon_Catalyst_Vorpal" },
  { id: 14412, icon: "UI_EquipIcon_Catalyst_Everfrost" },
  { id: 14417, icon: "UI_EquipIcon_Catalyst_Arakalari" },
  { id: 14414, icon: "UI_EquipIcon_Catalyst_Bakufu" },
  { id: 340001, icon: "UI_EquipIcon_Catalyst_MorphIlia_Wind" },
  { id: 14407, icon: "UI_EquipIcon_Catalyst_Exotic" },
  { id: 14415, icon: "UI_EquipIcon_Catalyst_Jyanome" },
  { id: 380001, icon: "UI_EquipIcon_Catalyst_Kristall" },
  { id: 14406, icon: "UI_EquipIcon_Catalyst_Proto" },
  { id: 14431, icon: "UI_EquipIcon_Catalyst_Isikhulu" },
  { id: 14404, icon: "UI_EquipIcon_Catalyst_Theocrat" },
  { id: 14403, icon: "UI_EquipIcon_Catalyst_Fossil" },
  { id: 14424, icon: "UI_EquipIcon_Catalyst_Yue" },
  { id: 14405, icon: "UI_EquipIcon_Catalyst_Resurrection" },
  { id: 14402, icon: "UI_EquipIcon_Catalyst_Troupe" },
  { id: 14416, icon: "UI_EquipIcon_Catalyst_Pleroma" },
  { id: 14430, icon: "UI_EquipIcon_Catalyst_Umpakati" },
  { id: 14410, icon: "UI_EquipIcon_Catalyst_Outlaw" },
  { id: 12416, icon: "UI_EquipIcon_Claymore_Maria" },
  { id: 320001, icon: "UI_EquipIcon_Claymore_MorphGravitas_Wind" },
  { id: 12408, icon: "UI_EquipIcon_Claymore_Blackrock" },
  { id: 12431, icon: "UI_EquipIcon_Claymore_Isikhulu" },
  { id: 12401, icon: "UI_EquipIcon_Claymore_Zephyrus" },
  { id: 12432, icon: "UI_EquipIcon_Claymore_Polilith" },
  { id: 12417, icon: "UI_EquipIcon_Claymore_Arakalari" },
  { id: 12430, icon: "UI_EquipIcon_Claymore_Umpakati" },
  { id: 12414, icon: "UI_EquipIcon_Claymore_Bakufu" },
  { id: 12410, icon: "UI_EquipIcon_Claymore_Lapis" },
  { id: 12412, icon: "UI_EquipIcon_Claymore_MillenniaTuna" },
  { id: 12418, icon: "UI_EquipIcon_Claymore_Fleurfair" },
  { id: 12415, icon: "UI_EquipIcon_Claymore_Pleroma" },
  { id: 12433, icon: "UI_EquipIcon_Claymore_Ilmarinen" },
  { id: 12427, icon: "UI_EquipIcon_Claymore_Mechanic" },
  { id: 12406, icon: "UI_EquipIcon_Claymore_Proto" },
  { id: 12405, icon: "UI_EquipIcon_Claymore_Perdue" },
  { id: 12404, icon: "UI_EquipIcon_Claymore_Theocrat" },
  { id: 12403, icon: "UI_EquipIcon_Claymore_Fossil" },
  { id: 12409, icon: "UI_EquipIcon_Claymore_Kione" },
  { id: 12411, icon: "UI_EquipIcon_Claymore_Dragonfell" },
  { id: 12424, icon: "UI_EquipIcon_Claymore_BeastTamer" },
  { id: 12402, icon: "UI_EquipIcon_Claymore_Troupe" },
  { id: 12425, icon: "UI_EquipIcon_Claymore_Vorpal" },
  { id: 390001, icon: "UI_EquipIcon_Claymore_VarkaTunkeldegen" },
  { id: 12407, icon: "UI_EquipIcon_Claymore_Exotic" },
  { id: 12426, icon: "UI_EquipIcon_Claymore_Champion" },
  { id: 13424, icon: "UI_EquipIcon_Pole_Shanty" },
  { id: 13404, icon: "UI_EquipIcon_Pole_Blackrock" },
  { id: 13403, icon: "UI_EquipIcon_Pole_Exotic" },
  { id: 13405, icon: "UI_EquipIcon_Pole_Gladiator" },
  { id: 13426, icon: "UI_EquipIcon_Pole_Caduceus" },
  { id: 13401, icon: "UI_EquipIcon_Pole_Stardust" },
  { id: 13409, icon: "UI_EquipIcon_Pole_Everfrost" },
  { id: 13407, icon: "UI_EquipIcon_Pole_Zephyrus" },
  { id: 13431, icon: "UI_EquipIcon_Pole_Isikhulu" },
  { id: 13414, icon: "UI_EquipIcon_Pole_Bakufu" },
  { id: 13406, icon: "UI_EquipIcon_Pole_Lapis" },
  { id: 13419, icon: "UI_EquipIcon_Pole_Windvane" },
  { id: 13417, icon: "UI_EquipIcon_Pole_Arakalari" },
  { id: 13430, icon: "UI_EquipIcon_Pole_Umpakati" },
  { id: 13427, icon: "UI_EquipIcon_Pole_Mechanic" },
  { id: 13433, icon: "UI_EquipIcon_Pole_Ilmarinen" },
  { id: 13402, icon: "UI_EquipIcon_Pole_Proto" },
  { id: 13425, icon: "UI_EquipIcon_Pole_Vorpal" },
  { id: 13408, icon: "UI_EquipIcon_Pole_Theocrat" },
  { id: 13434, icon: "UI_EquipIcon_Pole_Krivule" },
  { id: 330001, icon: "UI_EquipIcon_Pole_MorphSpinifer_Wind" },
  { id: 13432, icon: "UI_EquipIcon_Pole_Aoandon" },
  { id: 13416, icon: "UI_EquipIcon_Pole_Maria" },
  { id: 13415, icon: "UI_EquipIcon_Pole_Mori" },
  { id: 11414, icon: "UI_EquipIcon_Sword_Bakufu" },
  { id: 11408, icon: "UI_EquipIcon_Sword_Blackrock" },
  { id: 11432, icon: "UI_EquipIcon_Sword_SacrificialNgombe" },
  { id: 11415, icon: "UI_EquipIcon_Sword_Opus" },
  { id: 11401, icon: "UI_EquipIcon_Sword_Zephyrus" },
  { id: 11413, icon: "UI_EquipIcon_Sword_Magnum" },
  { id: 11425, icon: "UI_EquipIcon_Sword_Vorpal" },
  { id: 11426, icon: "UI_EquipIcon_Sword_Machination" },
  { id: 11431, icon: "UI_EquipIcon_Sword_Isikhulu" },
  { id: 11407, icon: "UI_EquipIcon_Sword_Exotic" },
  { id: 11416, icon: "UI_EquipIcon_Sword_Youtou" },
  { id: 11405, icon: "UI_EquipIcon_Sword_Rockkiller" },
  { id: 11434, icon: "UI_EquipIcon_Sword_Miekka" },
  { id: 11406, icon: "UI_EquipIcon_Sword_Proto" },
  { id: 11404, icon: "UI_EquipIcon_Sword_Theocrat" },
  { id: 11403, icon: "UI_EquipIcon_Sword_Fossil" },
  { id: 11417, icon: "UI_EquipIcon_Sword_Arakalari" },
  { id: 11433, icon: "UI_EquipIcon_Sword_Ilmarinen" },
  { id: 310001, icon: "UI_EquipIcon_Sword_MorphVinces_Wind" },
  { id: 11430, icon: "UI_EquipIcon_Sword_Umpakati" },
  { id: 11412, icon: "UI_EquipIcon_Sword_Psalmus" },
  { id: 11428, icon: "UI_EquipIcon_Sword_Purewill" },
  { id: 11410, icon: "UI_EquipIcon_Sword_Outlaw" },
  { id: 11409, icon: "UI_EquipIcon_Sword_Bloodstained" },
  { id: 11427, icon: "UI_EquipIcon_Sword_Mechanic" },
  { id: 11402, icon: "UI_EquipIcon_Sword_Troupe" },
  { id: 11422, icon: "UI_EquipIcon_Sword_Kasabouzu" },
  { id: 11424, icon: "UI_EquipIcon_Sword_Boreas" },
  { id: 11418, icon: "UI_EquipIcon_Sword_Pleroma" },
  { id: 15305, icon: "UI_EquipIcon_Bow_Msg" },
  { id: 15301, icon: "UI_EquipIcon_Bow_Crowfeather" },
  { id: 15303, icon: "UI_EquipIcon_Bow_Curve" },
  { id: 15302, icon: "UI_EquipIcon_Bow_Arjuna" },
  { id: 15304, icon: "UI_EquipIcon_Bow_Sling" },
  { id: 14304, icon: "UI_EquipIcon_Catalyst_Jade" },
  { id: 14301, icon: "UI_EquipIcon_Catalyst_Intro" },
  { id: 14303, icon: "UI_EquipIcon_Catalyst_Lightnov" },
  { id: 14302, icon: "UI_EquipIcon_Catalyst_Pulpfic" },
  { id: 14305, icon: "UI_EquipIcon_Catalyst_Phoney" },
  { id: 12302, icon: "UI_EquipIcon_Claymore_Siegfry" },
  { id: 12305, icon: "UI_EquipIcon_Claymore_Reasoning" },
  { id: 12301, icon: "UI_EquipIcon_Claymore_Glaive" },
  { id: 12306, icon: "UI_EquipIcon_Claymore_Mitsurugi" },
  { id: 12303, icon: "UI_EquipIcon_Claymore_Tin" },
  { id: 13303, icon: "UI_EquipIcon_Pole_Noire" },
  { id: 13302, icon: "UI_EquipIcon_Pole_Halberd" },
  { id: 13301, icon: "UI_EquipIcon_Pole_Ruby" },
  { id: 11301, icon: "UI_EquipIcon_Sword_Steel" },
  { id: 11304, icon: "UI_EquipIcon_Sword_Darker" },
  { id: 11305, icon: "UI_EquipIcon_Sword_Sashimi" },
  { id: 11302, icon: "UI_EquipIcon_Sword_Dawn" },
  { id: 11306, icon: "UI_EquipIcon_Sword_Mitsurugi" },
  { id: 11303, icon: "UI_EquipIcon_Sword_Traveler" },
];

async function download(url, path) {
  if (existsSync(path)) {
    console.log(`  SKIP ${path}`);
    return;
  }
  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.log(`  FAIL ${url} (${res.status})`);
      return;
    }
    const data = await res.arrayBuffer();
    await writeFile(path, Buffer.from(data));
    console.log(`  OK   ${path}`);
  } catch (e) {
    console.log(`  ERR  ${url}: ${e.message}`);
  }
}

async function main() {
  console.log(`Characters: ${CHARACTERS.length}, Weapons: ${WEAPONS.length}`);
  console.log('Downloading character assets...');
  for (const char of CHARACTERS) {
    const dir = `${PUBLIC}/characters/${char.id}`;
    await mkdir(dir, { recursive: true });

    // Icon
    await download(`${YATTA_CDN}/${char.icon}.png`, `${dir}/icon.png`);
    // Side icon
    await download(`${YATTA_CDN}/${char.sideIcon}.png`, `${dir}/side.png`);
    // Gacha splash art
    await download(`${YATTA_CDN}/UI_Gacha_AvatarImg_${char.avatarKey}.png`, `${dir}/gacha.png`);
  }

  console.log('\nDownloading weapon assets...');
  for (const weapon of WEAPONS) {
    const dir = `${PUBLIC}/weapons/${weapon.id}`;
    await mkdir(dir, { recursive: true });
    await download(`${YATTA_CDN}/${weapon.icon}.png`, `${dir}/icon.png`);
  }

  console.log('\nDownloading element icons...');
  const dir = `${PUBLIC}/elements`;
  await mkdir(dir, { recursive: true });

  // Element vision icons from yatta.moe assets
  const elements = {
    pyro: 'UI_Buff_Element_Fire',
    hydro: 'UI_Buff_Element_Water',
    anemo: 'UI_Buff_Element_Wind',
    electro: 'UI_Buff_Element_Electric',
    cryo: 'UI_Buff_Element_Ice',
    geo: 'UI_Buff_Element_Rock',
    dendro: 'UI_Buff_Element_Grass',
  };
  for (const [name, key] of Object.entries(elements)) {
    await download(`${YATTA_CDN}/${key}.png`, `${dir}/${name}.png`);
  }

  console.log('\nDone!');
}

main();
